--- #---------------------------
#---------------------------
# Hexo Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# Docs：https://hexo.fluid-dev.com/docs/guide/
#---------------------------

#---------------------------
# 全局
# Site
favicon: /img/favicon.ico # 网站标签页的 icon

apple_touch_icon: /img/favicon.ico # 用于苹果设备的 icon

title_join_string: " - " # 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名

force_https: false # 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）

highlight: # 代码高亮
  enable: true
  style: "Github Gist" # 高亮样式见：https://highlightjs.org/static/demo/  在页面挑选 style 填入
  bg_color: false # 是否根据 style 改变代码背景色，**如果 style 是深色背景别忘了开启此项**
  copy_btn: true # 是否开启复制代码的按钮

fun_features: # 一些好玩的功能
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度，数字越大越慢
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果
  anchorjs: # 为文章内容中的标题添加锚图标
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right # icon放置的位置： left | right
    visible: hover # 默认悬浮显示，可选：hover（鼠标在元素上悬浮时显示） | always（一直显示） | touch（移动端触摸显示）
    icon: "" # 可选：§ | # | ❡ 等，留空则为默认效果
  mouse_click: # 鼠标点击动效
    enable: false
    style: values # 目前设置两个值：values（价值观词汇） | love（爱心）

dark_mode: # 主题暗色模式，开启后菜单中会出现切换按钮，用户浏览器会存储切换选项，并且会遵循 prefers-color-scheme 自动切换
  enable: true
  default: auto # 默认的模式：auto | light | dark，选择 auto 时优先遵循 prefers-color-scheme，其次按用户本地时间 18 点到次日 6 点之间进入暗色模式，**注意：当用户手动切换后则不再按照默认模式**

color: # 主题颜色配置，不一定能每一处都生效，可能会被局部样式覆盖，这种情况建议用自定义 css 解决。配色可以在这获得启发： https://www.webdesignrankings.com/resources/lolcolors/
  body_bg_color: "#eee" # body 背景色
  body_bg_color_dark: "#181c27" # 暗色模式下的 body 背景色，下同
  navbar_bg_color: "#2f4154" # 顶部菜单背景色
  navbar_bg_color_dark: "#1f3144"
  navbar_text_color: "#fff" # 顶部菜单字体色
  navbar_text_color_dark: "#d0d0d0"
  text_color: "#3c4858" # 全局字体色
  text_color_dark: "#c4c6c9"
  sec_text_color: "#718096" # 全局次级字体色（摘要、简介等位置）
  sec_text_color_dark: "#a7a9ad"
  post_text_color: "#2c3e50" # 文章正文字体色
  post_text_color_dark: "#c4c6c9"
  post_heading_color: "#1a202c" # 文章标题标签字体色（h1 h2 h3...）
  post_heading_color_dark: "#c4c6c9"
  post_link_color: "#0366d6" # 文章超链接字体色
  post_link_color_dark: "#1589e9"
  link_hover_color: "#30a9de" # 超链接悬浮时字体色
  link_hover_color_dark: "#30a9de"
  link_hover_bg_color: "#f8f9fa" # 超链接悬浮背景色
  link_hover_bg_color_dark: "#364151"
  board_color: "#fff" # 主面板背景色
  board_color_dark: "#252d38"

font: # 主题字体配置
  font_size: 16px # 全局字号
  font_family: # 全局字体
  code_font_size: 85% # 代码的字号

custom_js: # 指定自定义 js 文件路径，路径是相对 source 目录，如 /js/custom.js 对应存放目录 source/js/custom.js，支持列表
custom_css: # 指定自定义 css 文件路径，路径是相对 source 目录，如 /css/custom.css 同上，支持列表
custom_html: "" # 自定义底部 HTML 内容（位于 footer 上方），也可用于外部引入 js css 这些操作，注意不要和 post.custom 配置冲突



web_analytics: # 网页访问统计
  enable: true
  baidu: # 百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
  google: UA-177243668-2 # Google 统计的 Tracking ID，参见 https://analytics.google.com/analytics/web/
  gtag: UA-177243668-2 # Google gtag.js 的媒体资源 ID，参见 https://analytics.google.com/analytics/web/ 中的 管理 -> 媒体资源设置 -> 跟踪 ID
  tencent: # 腾讯统计的 H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage (开启高级功能才有cid)
    sid:
    cid:
  woyaola: # 51.la 站点统计 ID，参见 https://www.51.la/user/site/index
  cnzz: # 友盟/cnzz 站点统计 web_id，参见 https://web.umeng.com/main.php?c=site&a=show
  leancloud: # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
    app_id:
    app_key:
    server_url: # REST API 服务器地址，国际版不填


lazyload: # 对页面中的图片进行懒加载处理，可见范围外的图片不会加载
  enable: true
  onlypost: false # 仅在文章页使用懒加载，开启后如果自定义页面需要使用，可以在 Front-matter 里指定 `lazyload: true`

daovoice: # 在线客服 Daovoice 参考：http://dashboard.daovoice.io
  enable: false # 是否开启在线客服聊天
  appid: "" # 应用 ID 设置

aplayer: # 音乐播放器，注意不能与 hexo-tag-aplayer 插件共用
  enable: false
  autoplay: false # 音频自动播放
  loop: "all" # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: "random" # 播放顺序，可选值: 'list', 'random'
  theme: "#b7daff" # 主题色
  songs: # 歌曲列表，必须传入下列各参数，其中 url 与 cover 在本地需存于 source 目录，更多参数见文档：https://aplayer.js.org/#/zh-Hans/?id=%E5%8F%82%E6%95%B0
    - {
        name: "name",
        artist: "artist",
        url: "/songs/test.mp3",
        cover: "/img/cover.jpg",
      }
    - {
        name: "name",
        artist: "artist",
        url: "https://...url.mp3",
        cover: "https://...cover.jpg",
      }

version: # 主题版本相关
  check: false # 每次生成页面后，检测主题是否为最新版本

#---------------------------
# 页头
# Header
#---------------------------
navbar:
  blog_title: Hackyboiz # 导航栏左侧的标题，为空则按 hexo config.title 显示
  ground_glass: # 导航栏毛玻璃特效，实验性功能，可能会造成页面滚动掉帧和抖动，部分浏览器不支持会自动不生效
    enable: false
    px: 3 # 模糊像素，只能为数字，数字越大模糊度越高
    alpha: 0.7 # 透明度，只能为数字，范围 0~1，数字越大透明度越低，注意透明过度可能看不清菜单字体
  menu: # 可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - {
        key: "category",
        link: "/categories/",
        icon: "iconfont icon-category-fill",
      }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-addrcard" }
    - { key: "author", link: "/author/", icon: "iconfont icon-user-fill" } # 友链页，把前面#去掉即可展示

search: # 搜索栏，基于 hexo-generator-search 插件，若已安装其他搜索插件请关闭此功能，以避免生成多余的索引文件。
  enable: true
  path: /local-search.xml # 文件引用地址，默认是下方生成位置，也可以将生成后的 local-search.xml 上传到其它位置引用，如：https://www.example.com/local-search.xml
  generate_path: /local-search.xml # 文件生成位置，必须为相对位置
  field: post
  content: true

scroll_down_arrow: # 向下滚动的箭头
  enable: true
  banner_height_limit: 90 # 头图高度不小于指定比例，才显示箭头
  scroll_after_turning_page: true # 翻页后自动滚动

banner_parallax: true # 头图滚动视差

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  statistics: # 展示网站的 PV、UV 统计数
    enable: false
    source: "busuanzi" # 统计数据来源，可选：busuanzi | leancloud，使用 leancloud 需要在 web_analytics 中设置 api 参数，使用 busuanzi 注意可能间歇抽风
    pv_format: "总访问量 {} 次" # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

  beian: # The footer of China's website policy, other areas keep disable
    enable: false
    icp_text: 京ICP证123456号 # ICP证号
    police_text: 京公网安备12345678号 # 公安备案号，不填则只显示ICP
    police_code: 12345678 # 公安备案的编号，用于URL跳转查询
    police_icon: /img/police_beian.png # 公安备案的图片. 为空时不显示备案图片

scroll_top_arrow: # 向顶部滚动的箭头
  enable: true

#---------------------------
# 首页
# Index Page
#---------------------------
index:
  banner_img: /img/default.png # 首页 Banner 头图，以下相同
  banner_img_height: 40 # 头图高度，屏幕百分比，available: 0 - 100
  banner_mask_alpha: 0.3 # 头图黑色蒙版的透明度，available: 0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  post_default_img: "" # 默认的文章封面图，当没有指定 index_img 时会使用该图片，若都为空则不显示任何图片
  slogan: # 首页副标题的独立设置
    enable: true # 为 false 则不显示任何内容
    text: "Welcome to Hackyboiz" # 为空则按 hexo config.subtitle 显示
  auto_excerpt:
    enable: true
  post_url_target: _self # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: true
    tag: true

# 通过 hexo new page 命令创建的页面
# Custom Page
page:
  banner_img: /img/default.png
  banner_img_height: 40 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0

#---------------------------
# 文章页
# Post Page
#---------------------------
post: # 部分配置同时控制自定义页面，注意备注
  banner_img: /img/default.png
  banner_img_height: 40 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0
  meta: # 文章标题下方的信息
    date: # 文章日期
      enable: true
      format: "LL a" # 格式参照 ISO-8601 日期格式化，可参照 http://momentjs.cn/docs/#/parsing/string-format/
    wordcount: # 字数统计
      enable: true
      format: "{} 자" # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read: # 阅读时间
      enable: true
      format: "{} 분"
      words: 100 # 每分钟阅读多少字，如果是技术文章，建议降低
    views: # 阅读次数
      enable: false
      source: "busuanzi" # 统计数据来源，可选：busuanzi | leancloud，使用 leancloud 需要在 web_analytics 中设置 api 参数，使用 busuanzi 注意可能间歇抽风
      format: "{} 읽음"
  updated: # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
    enable: false
    content: 本文最后更新于： # 描述文字
    relative: false # 是否使用相对时间表示，比如："3 天前"
  toc: # 文章右侧目录
    enable: true
    headingSelector: h1,h2,h3,h4,h5,h6
    collapseDepth: 0 # 层级的折叠深度，0 是全部折叠，6 是全部不折叠
  copyright: # 版权声明
    enable: true
    content: '본 글은 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.ko" rel="nofollow noopener">CC BY-SA 4.0</a> 라이선스로 배포됩니다. 공유 또는 변경 시 반드시 출처를 남겨주시기 바랍니다.'
  prev_next: # 文章底部上一篇下一篇功能
    enable: true
  custom: # 文章底部自定义内容
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # 自定义区域，支持 HTML，可自行插入赞赏码、公众号二维码等内容
  image_zoom: # 文章图片可点击放大
    enable: true # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `image_zoom: true`，并且图片使用该格式插入：<img src="..." zoom />
  footnote: # 脚注语法，会在文章底部生成脚注，如果 Markdown 渲染器本身支持，则建议关闭，否则可能会冲突
    enable: true
    header: "" # 脚注的节标题，也可以在 front-matter 中通过 `footnote: <h2>Reference</h2>` 这种形式修改单页的节标题
  math: # 数学公式，开启之前需要更换 Markdown 渲染器，否则复杂公式会有兼容问题，具体请见：https://hexo.fluid-dev.com/docs/guide/##latex-数学公式
    enable: true # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `math: true`
    specific: false # 开启后，只有在文章 Front-matter 里指定 `math: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    engine: mathjax # 公式引擎  available: mathjax | katex
  mermaid: # 流程图，基于 mermaid-js，文档：http://mermaid-js.github.io/mermaid/
    enable: false # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `mermaid: true`
    specific: false # 开启后，只有在文章 Front-matter 里指定 `mermaid: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    options: { theme: "default" } # 接口选项，具体可见：http://mermaid-js.github.io/mermaid/#/mermaidAPI
  comments: # 评论
    enable: true # 开启评论
    type: disqus # 指定使用的评论模块  available: disqus | valine | gitalk | utterances | changyan | livere | remark42

#---------------------------
# 评论
# Comments
#---------------------------

# 开启评论需要先在上方 post.comments.enable: true

# utterances
# You can install utterances with https://utteranc.es/ and generate your configuration
utterances:
  repo:
  issue_term: pathname
  label: utterances
  theme: github-light
  crossorigin: anonymous

# Disqus
disqus:
  shortname: hackyboiz
  # The following are Disqusjs configurations, please ignore if DisqusJS is not required
  # 以下为 Disqusjs 支持, 国内用户如果想使用 Disqus 建议配合使用
  # https://github.com/SukkaW/DisqusJS
  disqusjs: false # 设置为 true 开启 DisqusJS
  apikey: # DisqusJS 向 API 发起请求时使用的 API Key
  count: true
  lazyload: false

# Gitalk
# You can get yout ClientID and ClientSecret from https://github.com/settings/applications/new
# More info available at https://github.com/gitalk/gitalk#options
gitalk:
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo: # The repo to store comments
  owner: # GitHub repository owner. Can be personal user or organization.
  admin: ["name"] # GitHub repo owner and collaborators, only these guys can initialize github issues, should be like ['admin'] or ['admin1','admin2']
  id: location.pathname # The unique id of the page. Length must less than 50.
  language: ko-KR # Localization language key, en, zh-CN and zh-TW are currently available.
  labels: ["Gitalk"] # GitHub issue labels.
  perPage: 10 # Pagination size, with maximum 100.
  pagerDirection: last # Comment sorting direction, available values are last and first.
  distractionFreeMode: false # Facebook-like distraction free mode.
  createIssueManually: true # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true.

# Valine
# 完整文档 https://valine.js.org/configuration.html
# 注意：下列配置项中的 true/false 不要用引号括起来
valine:
  appid: # 从 LeanCloud 的应用中得到的 appId
  appkey: # 从 LeanCloud 的应用中得到的 APP Key
  placeholder: 说点什么 # 评论框占位提示符
  path: window.location.pathname # 当前文章页路径，用于区分不同的文章页，以保证正确读取该文章页下的评论列表
  avatar: retro # Gravatar 头像展示方式
  meta: ["nick", "mail", "link"] # 评论者相关属性
  pageSize: 10 # 评论列表分页，每页条数
  lang: en # zh-CN | zh-TW | en | ja
  highlight: false # 代码高亮
  recordIP: false # 是否记录评论者IP
  serverURLs: # REST API 服务器地址，国际版不填

# 畅言
# http://changyan.kuaizhan.com/
changyan:
  appid: ""
  appkey: ""

# Livere 来必力
# You can get your uid from https://www.livere.com/my_Livere
livere:
  uid: ""

# Remark42
# https://remark42.com/
remark42:
  host: https://remark.haoyizebo.com
  site_id: haoyizebo
  max_shown_comments: 10
  locale: ko

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  banner_img_height: 40 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0
  subtitle: # 打字机内容

#---------------------------
# 分类归档页
# Categories Page
#---------------------------
category:
  banner_img: /img/default.png
  banner_img_height: 40 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0
  subtitle: # 打字机内容
  post_limit: 10 # 单个分类中折叠展示文章数的最大值，超过限制会显示 More
  order_by: "-length" # 排序字段，前面带减号是倒序，不带减号是正序，可选项：name | length

#---------------------------
# 标签归档页
# Tags Page
#---------------------------
tag:
  banner_img: /img/default.png
  banner_img_height: 40 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0
  subtitle: # 打字机内容
  tagcloud: # 标签云
    min_font: 15
    max_font: 30
    unit: px # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  banner_img: /img/default.png
  banner_img_height: 40 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0
  subtitle: # 打字机内容
  avatar: /img/avatar.png # 头像
  name: hackyboiz
  introduce: "트렌드를 따라가(고자 노력하)는 악동들..☆</br></br>Hackyboiz 페이스북 페이지 : <a href=\"https://www.facebook.com/hackyboiz\"> https://www.facebook.com/hackyboiz</a></br>Hackyboiz 블로그 : <a href=\"http://hackyboiz.github.io\">http://hackyboiz.github.io</a></br>해킹짹짹 인스타 : <a href=\"https://www.instagram.com/hacking.jjackjjack/\">https://www.instagram.com/hacking.jjackjjack</a></br>해킹짹짹 뉴스레터 구독 : <a href=\"https://page.stibee.com/subscriptions/130678\">https://page.stibee.com/subscriptions/130678</a></br>지난 뉴스레터 보기 : <a href=\"https://page.stibee.com/archives/130678\">https://page.stibee.com/archives/130678</a>"
  icons:
    - {
        class: "iconfont icon-github-fill",
        link: "https://github.com/hackyboiz",
        tip: "GitHub",
      }
    - {
        class: "iconfont icon-mail",
        link: "mailto:hackrssteam@gmail.com",
        tip: "Email",
      }
    - {
        class: "iconfont icon-th-large",
        link: "https://hackrss.kr",
        qrcode: "/img/logo192.png",
      }

#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: /img/default.png
  banner_img_height: 85 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0
  subtitle: "Page not found" # 打字机内容

#---------------------------
# 友链页
# Links Page
#---------------------------
author:
  banner_img: /img/default.png
  banner_img_height: 40 # available: 0 - 100
  banner_mask_alpha: 0.3 # available: 0 - 1.0
  subtitle: # 打字机内容
  items: # intro 与 image 可省略
    - {
        title: "L0ch",
        email: "bsms0418@icloud.com",
        git: "https://github.com/L0ch",
        intro: "바다가 되고 싶은 호수이다.</br>포너블을 주로 하며 요즘은 윈도우 취약점을 공부하고 있다.</br>맥북 사놓고 가상 머신으로 윈도우를 돌려 공부를 하는 기이한 행동을 한다.",
        image: "/img/profile_L0ch.jpg",
      }
    - {
        title: "pwndorei",
        email: "lkjuio3865@gmail.com",
        git: "https://github.com/pwndorei",
        intro: "항상 검은색 모자와 검은 티를 입고 음흉한 미소를 짓는다.<br>본인은 부정하지만 dorei는 도라이라는 뜻인 듯 하다. pwn도 pwnable이 아닌 다른 의미라고 하는데.. 여러분의 상상에 맡긴다.",
        image: "/img/profile_pwndorei.jpg",
      }
    - {
        title: "hunjison",
        email: "esby9774@gmail.com",
        git: "https://github.com/hunjison",
        intro: "한 때 인플루언서를 꿈꾸던 훈지손이다.</br>호기심이 많아 일 벌이기를 잘하지만, 뒷처리를 감당하기 힘들어한다.</br>현재 포렌식 과거를 청산하고 임베디드 취약점을 분석하고 있다.",
        image: "/img/profile_hunjison.png",

      }
    - {
        title: "ogu123",
        email: "njs414@naver.com",
        git: "",
        intro: "",
        image: "/img/profile_ogu123.jpg",
      }
    - {
        title: "CHIMITA",
        email: "ch1m1taaaaa@gmail.com",
        git: "https://github.com/CHIMITA",
        intro: "관심 분야가 많고 계속 깨어있어서, 지원을 요청하면 일단 보내보라며 후다닥 지원해준다.</br>단 너무 많은 지원을 요청하면 파업함(지원 오버플로우)",
        image: "/img/profile_chimita.png",
      }
    - {
        title: "romi0x",
        email: "ii887742@gmail.com",
        git: "https://github.com/ddddabi",
        intro: "하고싶은게 많아 찍먹을 좋아한다.</br>개발과 보안 융합을 하고싶어 한다.</br>스불재 인생을 살아가고있다.",
        image: "/img/profile_romi0x.jpg"
      } 
    - {
        title: "syru",
        email: "mail@syru.dev",
        git: "https://github.com/l0vey0u",
        intro: "이건 왜지? </br> 그가 제일 자주하는 말이다. </br>웹만 팔 줄 알고 시스템을 무시했지만 시스템 공부의 필요성을 느껴 후회의 눈물을 흘리며 공부중이다.",
        image: "/img/profile_syru.jpg",
      }
    - {
        title: "j0ker",
        email: "pwnbatman@gmail.com",
        git: "https://github.com/pwnbatman-joker",
        intro: "믿거 조 씨 집안 28대손 조-커.</br>대외적으로 노출되는 것을 극도로 싫어한다.</br>계단을 내려갈 때 춤을 추면서 내려간다.(왜 그러는지는 아무도 모른다.)",
        image: "/img/profile_j0ker.jpg",
      }
    - {
        title: "idioth",
        email: "dbsghdrhks78@gmail.com",
        git: "https://github.com/idioth",
        intro: "<del>약간 모자라서 모자를 자주 쓰고 다닌다.</del></br>리버싱과 악성코드 분석에 관심이 많으며 슬플 때 힙합 노래를 듣는다.</br>팀장이지만 팀원들에게 무시당하는 삶을 살고 있다.",
        image: "/img/profile_idioth.jpg",
      }
    - {
        title: "Fabu1ous",
        email: "gregmj@naver.com",
        git: "https://github.com/Greg-Kim",
        intro: "포너블 외길 인생이며 기타를 매우 잘친다.</br>그가 기타로 꼬신 사람만 모아도 브루트 포싱이 가능할 정도라고..</br>막내를 탈출하고 싶어하지만 우리의 마음 속에는 영원한 막내이다.",
        image: "/img/profile_Fabu1ous.jpg",
      }
    - {
        title: "poosic",
        email: "fkfkvktm310@naver.com",
        git: "https://github.com/poosic",
        intro: "\"선글라스 없이 그를 바라보는 건 불가능에 가깝다.\"</br>그를 직접 본 사람들은 모두 그렇게 말한다.</br>너무 빛나는 외모 탓에 사람들은 그를 바라보기를 포기했다.</br>결국 주위에 사람이 없어진 그는 컴퓨터에 몰두하게 되는데...",
        image: "/img/profile_poosic.jpg",
      }
    - {
        title: "y00n_nms",
        email: "qorengkssk@naver.com",
        git: "https://github.com/Yoon1021",
        intro: "포너블, 리버싱, 암호에 발목만 담그고 놀고 있으며 지난 과거를 청산(어떤 과거인지는 상상에 맡긴다.)하고</br>선량하게 살기를 노력하고 있다.</br>hackyboiz의 고양이(모자 아님)을 그린 사람으로 아주 까만 네로를 좋아한다.</br>매우 카와이한 외모를 가지고 있다.</br>nms의 뜻은 need more sleep이라고 한다.",
        image: "/img/profile_y00n_nms.jpg",
      }
    - {
        title: "Paol",
        email: "admln@kakao.com",
        git: "",
        intro: "팀 내 최연장자이며 본인 피셜 꼰대라고 한다.</br>그래서 그런지 라떼를 사랑하는 모습을 볼 수 있다.</br>모습이 보이지 않다가 회식때만 나타나는 것을 보면 라떼보다 알코올을 더 사랑하는 것 같기도 하다.</br>회식 때 막내 poosic과 사라졌다가 1시간 뒤에 나타난 적이 있는데, 그 후 poosic이 착해졌다는 소문이...",
        image: "/img/profile_Paol.png",
      }
    - {
        title: "nanglam",
        email: "nang_lam@naver.com",
        git: "",
        intro: "",
        image: "/img/profile_nanglam.jpg",
      }
    - {
        title: "insu",
        email: "hpy.insu@gmail.com",
        git: "https://github.com/insu123",
        image: "/img/profile_insu.jpg",
      }
    - {
        title: "juntheworld",
        email: "",
        git: "",
        intro: "시스템해킹과 네트워크를 공부하고 있는 뉴비중의 뉴비다. </br>언젠가 해킹으로 세상을 정복하는게 꿈이다.</br> jun will make world",
        image: "/img/profile_juntheworld.jpg",

      }
    - {
        title: "D0hwQ1",
        email: "pjt137@naver.com",
        git: "https://github.com/d0hwq1",
        intro: "IT와 관련된 다양한 분야에서 모두 놀고 싶어하며, 잠도 줄여가며 포너블을 주로 공부하는 핵린이다.</br>정보보안 활동으로 명예와 부를 얻어 한량이 되는 것을 목표로 하고있다.",
        image: "/img/profile_D0hwQ1.jpg",

      }
    - {
        title: "IN'0Hack",
        email: "",
        git: "",
        image: "/img/profile_IN'0Hack.jpg",

      }

